Add kv260_imx219_sample application with Rust and C++ support
- Created a Makefile for the C++ application to handle build, clean, and run operations.
- Updated BIF and DTS files to reference the new sample bitstream and firmware names.
- Introduced Rust project structure with Cargo.toml and Cargo.lock for dependency management.
- Implemented main Rust application logic for interfacing with the IMX219 camera sensor.
- Added cross-compilation support in Rust using a dedicated Makefile.
- Updated Verilog testbench and RTL files to reflect the new sample naming conventions.
- Modified Vivado project file paths for consistency and improved implementation settings.

diff --git a/projects/kv260/kv260_imx219_v3/app/Makefile b/projects/kv260/kv260_imx219_v3/app/Makefile
--- a/projects/kv260/kv260_imx219_v3/app/Makefile
+++ b/projects/kv260/kv260_imx219_v3/app/Makefile
@@ -1,7 +1,8 @@
+TARGET_NAME = kv260_imx219_sample
 
-TARGET    = kv260_imx219.out
-DT_NAME   = kv260_imx219
-BIT_NAME  = kv260_imx219
+DT_NAME    = $(TARGET_NAME)
+BIT_NAME   = $(TARGET_NAME)
+ACCEL_NAME = $(TARGET_NAME)
 
 DTS_FILE  = $(DT_NAME).dts
 DTBO_FILE = $(DT_NAME).dtbo
@@ -10,46 +11,48 @@ BIT_FILE  = $(BIT_NAME).bit
 BIF_FILE  = $(BIT_NAME).bif
 BIN_FILE  = $(BIT_FILE).bin
 
-FIRMWARE_PATH = /lib/firmware
 DEVTREE_PATH  = /configfs/device-tree
+FIRMWARE_PATH = /lib/firmware
+ACCEL_PATH    = $(FIRMWARE_PATH)/xilinx/$(ACCEL_NAME)
 
-CFLAGS  += -Wall -g -O2 `pkg-config --cflags opencv4` -I../../../../include
-LDFLAGS += -g  `pkg-config --libs opencv4`
+KV260_SERVER_ADDRESS ?= 127.0.0.1:8051
 
 RUN_OPT ?=
 
-OBJS = main.o
-
-
 .PHONY: all
-all: $(TARGET) $(DTBO_FILE) $(BIN_FILE)
+all: $(DTBO_FILE) $(BIN_FILE)
+
+.PHONY: build
+build: $(DTBO_FILE) $(BIN_FILE)
 
 .PHONY: clean
 clean:
-	rm -rf $(TARGET) $(OBJS) $(DTBO_FILE) $(BIN_FILE)
+	rm -rf $(DTBO_FILE) $(BIN_FILE)
 
 .PHONY: run
-run: $(TARGET) load
-	./$(TARGET) $(RUN_OPT)
+run: run_cpp
+
+.PHONY: run_cpp
+run_cpp: load
+	make -C cpp run RUN_OPT="$(RUN_OPT)"
+
+.PHONY: build_cpp
+build_cpp:
+	make -C cpp build
 
 .PHONY: run_rust
 run_rust: load
-	cd rust; cargo run
+	cd rust; cargo run -- $(RUN_OPT)
 
 .PHONY: build_rust
 build_rust:
 	cd rust; cargo build
 
-.PHONY: server
-server: load
-	cd grpc/server; cargo run
+.PHONY: run_server
+run_server: load
+	cd grpc/server; cargo run RUN_OPT="$(RUN_OPT)"
 
 
-$(TARGET): $(OBJS)
-	g++ -o $(TARGET) $(OBJS) $(LDFLAGS)
-
-%.o : %.cpp
-	g++ $(CFLAGS) -c $< -o $@
 
 $(DTBO_FILE): $(DTS_FILE)
 	dtc -I dts -O dtb -o $(DTBO_FILE) $(DTS_FILE)
@@ -57,10 +60,65 @@ $(DTBO_FILE): $(DTS_FILE)
 $(BIN_FILE): $(BIF_FILE) $(BIT_FILE)
 	bootgen -w -image $(BIF_FILE) -arch zynqmp -process_bitstream bin
 
+$(BIT_FILE):
+	@if [ -f $@ ]; then \
+	    echo "$@ exists, skipping build"; \
+	elif command -v vivado >/dev/null 2>&1; then \
+	    echo "vivado found — building $@"; \
+	    make bit_cp -C ../syn/tcl; \
+	else \
+	    echo "vivado not found — cannot build $@"; \
+	    exit 1; \
+	fi
+
+.PHONY: load
+load: load_dfx
+
+.PHONY: unload
+unload: unload_dfx
+
+
+### DFX Management
+
+.PHONY: load_dfx
+load_dfx: $(DEVTREE_PATH) $(DTBO_FILE) $(BIN_FILE) unload_dfx
+	sudo mkdir -p $(ACCEL_PATH)
+	sudo cp $(BIN_FILE) $(ACCEL_PATH)
+	sudo cp $(DTBO_FILE) $(ACCEL_PATH)
+	sudo cp shell.json $(ACCEL_PATH)
+	sudo xmutil loadapp $(ACCEL_NAME)
+
+.PHONY: unload_dfx
+unload_dfx:
+	-sudo xmutil unloadapp
+
+.PHONY: unregister_accel
+unregister_accel:
+	sudo rm -f $(ACCEL_PATH)/$(BIT_FILE)
+	sudo rm -f $(ACCEL_PATH)/$(BIN_FILE)
+	sudo rm -f $(ACCEL_PATH)/$(DTBO_FILE)
+	sudo rm -f $(ACCEL_PATH)/shell.json
+	sudo rm -fd $(ACCEL_PATH)
+
+
+### Jelly loader
+
+.PHONY: load_jelly
+load_jelly: unload_jelly
+	jelly-fpga-loader unload --ip $(KV260_SERVER_ADDRESS)
+	jelly-fpga-loader register-accel $(ACCEL_NAME) $(DTBO_FILE) $(BIN_FILE) --ip $(KV260_SERVER_ADDRESS)
+	jelly-fpga-loader load $(ACCEL_NAME) --ip $(KV260_SERVER_ADDRESS)
+
+.PHONY: unload_jelly
+unload_jelly:
+	-jelly-fpga-loader unload --ip $(ZYBO_Z7_SERVER_ADDRESS)
+
+
+### Device Tree Overlay Management
+
 $(DEVTREE_PATH):
 	sudo mkdir -p /configfs
 	sudo mount -t configfs configfs /configfs
-
 
 .PHONY: mount
 mount: $(DEVTREE_PATH)
@@ -72,8 +130,8 @@ umount: unload
 		sudo umount /configfs ; \
 	fi
 
-.PHONY: load
-load: $(DEVTREE_PATH) $(DTBO_FILE) $(BIN_FILE) unload
+.PHONY: load_dt
+load_dt: $(DEVTREE_PATH) $(DTBO_FILE) $(BIN_FILE) unload
 	-sudo xmutil unloadapp
 	@if [ -e /configfs/device-tree/overlays/k26-starter-kits_image_1 ] ; then \
 		sudo rmdir /configfs/device-tree/overlays/k26-starter-kits_image_1 ; \
@@ -92,19 +150,10 @@ load: $(DEVTREE_PATH) $(DTBO_FILE) $(BIN_FILE) unload
 	sudo chmod 666 /dev/udmabuf*
 	sudo chmod 666 /dev/i2c-6
 
-.PHONY: unload
-unload:
+.PHONY: unload_dt
+unload_dt:
 	@if [ -e $(DEVTREE_PATH)/overlays/full ] ; then \
-		echo unload ; \
+		echo unload device tree overlay; \
 		sudo rmdir $(DEVTREE_PATH)/overlays/full ; \
 	fi
-
-.PHONY: load2
-load2: $(DTBO_FILE) $(BIN_FILE)
-	sudo fpgautil -R
-	sudo fpgautil -b $(BIT_FILE) -o $(DTBO_FILE)
-
-.PHONY: unload2
-unload2:
-	sudo fpgautil -R
 
